export enum EventType{
    USER_CREATED = "USER CREATED", //to create user
    USER_DELETED = "USER DELETED", //to delete user
    PRODUCT_SCANNED = "PRODUCT SCANNED", //on product scanned by reader
    READER_REQUESTED = "READER REQUESTED",
    READER_STARTED = " READER STARTED", //on start reader
    READER_STOPED = " READER STOPED", //on stop reader

    READER_REQUESTED_START = "START READER REQUESTED", //to start reader from client
    READER_REQUESTED_STOP = "STOP READER REQUESTED", //to stop reader from client
    READER_PRESENCE_REQUESTED = "READER PRESENCE REQUESTED",
    READER_PRESENCE_RESPONDED = "READER PRESENCE RESPONDED",

    ORDER_PLACED = "ORDER PLACED",
        ORDER_APPROVED = "ORDER APPROVED",
    ORDER_REJECTED = "ORDER REJECTED",

}

